### ISSUE TITLE
Think about units

### ISSUE THREAD

**Issue by samwaseda** [pyiron/elaston#22]
I think `elaston` is a good place to think about units, since incompatibility happens already at very low levels, and it is not an official package so we can still play around.

- Requirements
  - All functions must be unit-complete, i.e. the output unit must be a combination of input units
- Optional
  - Functions can require certain units
- Operations
  - Detection of the arguments with units
  - Conversion to the required units
  - Parsing of the output unit

Example: Stress field around a dislocation

Input: positions (`x`: Å), Burger’s vector (`b`: Å), elastic constants (`C`: GPa)
Output: stress field (GPa = `b / x * C`)

I’m actually not really sure to which extend we can streamline the procedure, so that potentially a general wrapper can be written.

Since my plane just landed, I will edit this issue later to finish writing down my thoughts.

**Comment by samwaseda** [comment]
I found out that there’s `wraps` in `pint.UnitRegistry`, which does more or less what I want. My problem is that it strongly binds to `pint`. In particular, when I call a function without any unit, I would like it to treat it as a normal function. Also, I would like to be able to put keywords, so that:

```python
@ureg.wraps(“second”, {“t”: “second”})
def get_time(t):
    return t * 2
```

Or `t = “second”`.

**Comment by samwaseda** [comment]
I guess I’m gonna now involve @liamhuber because this decorator is getting fairly close to the decorator in `pyiron_workflow`. In the final form, I would like to have something like:

```python
@units(inputs={“b”: “angstrom”, “x”: “angstrom”, “C”: “GPa”}, outputs={“stress”: “GPa”})
def get_stress_absolute(x, b, C):
    return b / x * C

@units(outputs={“stress”: “x / b * C”})
def get_stress_relative(x, b, C):
    return b / x * C
```

Then the following should happen:

```python
from pint import UnitRegistry
ureg = UnitRegistry()
print(“plain value:”, get_stress_absolute(1, 1, 1))  # This shouldn’t even invoke anything other than checking `ureg` was used anywhere
print(“explicit units:”, get_stress_absolute(1 * ureg.nanometer, 1 * ureg.angstrom, 1 * ureg.gigapascal))
print(“relative units:”, get_stress_relative(1 * ureg.nanometer, 1 * ureg.angstrom, 1 * ureg.gigapascal))
```

Output:

```
plain value: 1
explicit units: 10 gigapascal
relative units: 10 gigapascal
```

**Comment by liamhuber** [comment]
> I guess I’m gonna now involve @liamhuber because this decorator is getting fairly close to the decorator in `pyiron_workflow`. In the final form, I would like to have something like:
> 
> ```python
> @units(inputs={“b”: “angstrom”, “x”: “angstrom”, “C”: “GPa”}, outputs={“stress”: “GPa”})
> def get_stress_absolute(x, b, C):
>     return b / x * C
> 
> @units(outputs={“stress”: “x / b * C”})
> def get_stress_relative(x, b, C):
>     return b / x * C
> ```
> ...

At first glance, I think this will work fine. We'll need to double-check that there are no nasty side effects when it comes to pickling, but I expect double-decorating to work out-of-the-box:

```python
@Workflow.wrap.as_function_node("stress")
@units(inputs={“b”: “angstrom”, “x”: “angstrom”, “C”: “GPa”}, outputs={“stress”: “GPa”})
def get_stress_absolute(x, b, C):
    return b / x * C
```

So some awkwardnes double-labeling the output, but that is just sugar.

I'm a little less clear what the interaction is with `as_macro_node`... but to the extent that this internally uses `@units` wrapped function nodes, I can imagine there's simply nothing to do here.
